In [1]:
import numpy as np
from sklearn.datasets import load_diabetes
import matplotlib.pyplot as plt
from SOVBR import SOVBR

## Data load

In [2]:
diabetes = load_diabetes()
X, y = diabetes.data, diabetes.target
th = 400

## Model initialization and fitting

In [3]:
model = SOVBR(random_state=42)

In [4]:
model.fit(X[:th,:], y[:th], gamma=53, lam=4e-3, mode='monolithic', verbose=True)

Num of iterations is 340


In [7]:
# MAP
model.mu

array([ 4.94098490e-01, -1.37282819e+02,  4.93095698e+02,  2.95867911e+02,
       -2.14855747e+02, -1.26424806e-07, -1.81625564e+02,  4.43585154e+01,
        6.13446256e+02,  2.50830589e-08])

In [8]:
# Mean
model.m

array([  13.14068633, -141.65545108,  493.42402805,  294.90683133,
       -177.64735095,  -58.27870248, -177.58902924,   85.88729411,
        585.173606  ,    1.65485441])

In [9]:
# Covariance
model.C[:4,:4]

array([[ 2920.58024771,  -279.76178938,   -57.70716969,  -604.82109605],
       [ -279.76178938,  3500.62250235,   449.99885695,  -671.25680729],
       [  -57.70716969,   449.99885695,  4638.62904697, -1003.13553582],
       [ -604.82109605,  -671.25680729, -1003.13553582,  4254.0059073 ]])